# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install --upgrade setuptools
  - pip install pip --upgrade
  - pip install -r requirements/common.txt
  - pip install -r requirements/development.txt

# command to run tests, e.g. python setup.py test
script: tox
